fix(BBD-880): Search page doesn't load on refresh
groupby/storefront-breadcrumbs pull request #22
Opened 2017-12-14 19:40 UTC by zfcb

2017-12-19 15:17 UTC, Filip-F submitted a review, later dismissed

2017-12-19 15:17 UTC, Filip-F commented on test/unit/breadcrumbs.ts
> +      breadcrumbs.flux = <any>{ on };
In both this and the next test, why does on need to be a spy?

2017-12-19 15:17 UTC, Filip-F commented on test/unit/breadcrumbs.ts
> +      breadcrumbs.updateOriginalQuery = spy();
In this and the next 2 tests, why does this need to be a spy?

2017-12-20 22:12 UTC, Vic-Dev requested changes
Minor thing

2017-12-20 22:12 UTC, Vic-Dev commented on test/unit/breadcrumbs.ts
> +    it('should call updateOriginalQuery', () => {
`should call updateCorrectedQuery`

2017-12-20 22:21 UTC, Vic-Dev commented on src/breadcrumbs/index.ts
> +    if (originalQuery !== correctedQuery) {
Is there a way to refactor this so it only causes 1 update? Rather than 1 for corrected query and 2nd one for original query

2017-12-21 19:29 UTC, treeforever submitted a review, later dismissed

2017-12-22 17:06 UTC, merged